export default {
  siteName: 'BitMEX Bot',
  noData: 'No data',
  signIn: 'Sign in',
  signUp: 'Sign up',
  signOut: 'Sign out',
  home: 'Home',
  success: 'Success',
  error: 'Error',
  unknownServerError: 'Unknown server error',
  signInWithYourAccount: 'Sign in with your account',
  signUpToYourAccount: 'Sign up to your Account',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  username: 'Username',
  password: 'Password',
  invitationCode: 'Invitation Code',
  keepMeSignedIn: 'Keep me signed in',
  forgotPassword: 'Forgot password?',
  doNotHaveAnAccount: 'Do not have an account?',
  alreadyHaveAnAccount: 'Already have an account?',
  thisFieldIsRequired: 'This field is required',
  thisFieldIsInvalid: 'This field is invalid',
  yourEmailIsInvalid: 'Your Email is invalid',
  agreeTheTermsAndPolicy: 'Agree the terms and policy',
  pleaseAcceptThis: 'Please accept this',
  refresh: 'Refresh',
  adminPanel: 'Admin Panel',
  userManagement: 'User Management',
  dashboard: 'Dashboard',
  yes: 'Yes',
  no: 'No',
  back: 'Back',
  save: 'Save',

  deleteUser: 'Delete User',
  doYouWantToDelete: 'Do you want to delete?',

  addUser: 'Add User',
  editUser: 'Edit User',
  add: 'Add',
  edit: 'Edit',
  cancel: 'Cancel',
  thisEmailIsInvalid: 'This email is invalid',
  delete: 'Delete',

  newApiKey: 'New Api Key',
  createBot: 'Create Bot',
  startBot: 'Start Bot',
  editBot: 'Edit Bot',
  deleteBot: 'Delete Bot',
  stopBot: 'Stop Bot',

  registerBots: 'Register Bots',
  name: 'Name',
  exchange: 'Exchange',
  symbol: 'Symbol',
  apiKey: 'Api Key',
  apiKeySecret: 'Api Key Sercet',
  orderType: 'Order Type',
  strategy: 'Strategy',
  leverage: 'Leverage',
  quantity: 'Quantity',
  price: 'Price',
  tpPercent: 'T/P %',
  takeProfitPercent: 'Take Profit %',
  slPercent: 'S/L %',
  stopLossPercent: 'Stop Loss %',
  market: 'Market',
  limit: 'Limit',
  postOnly: 'Post Only',
  long: 'Long',
  short: 'Short',
  cross: 'Cross',
  custom: 'Custom',
  trailingStop: 'Trailing Stop %',
  numberOfSafeOrder: 'Number Of Safe Order',
  actionForLoss: 'Action For Loss',
  actionForProfit: 'Action For Profit',
  closeTheOrder: 'Close the order',
  openNewOrderOnStopLossPrice: 'Open new order on stop loss price',
  valueXOfLastCloseOrder: 'Value(X) Of Last Close Order',
  timesRepeatSameLogic: 'Times repeat same logic',
  breakdownPriceForNewOrder: 'Breakdown price for new order',
  timeIntervalAfterClose: 'Time interval after close',
  selectExchange: '(Select Exchange)',
  selectSymbol: '(Select Symbol)',
};
