export default {
  siteName: 'Profit Bot',
  noData: 'No data',
  signIn: 'Sign in',
  signUp: 'Sign up',
  signOut: 'Sign out',
  home: 'Home',
  success: 'Success',
  error: 'Error',
  successfullySaved: 'Successfully saved',
  successfullyCleared: 'Successfully cleared',
  unknownServerError: 'Unknown server error',
  signInWithYourAccount: 'Sign in with your account',
  signUpToYourAccount: 'Create your account',
  firstName: 'First Name',
  lastName: 'Last Name',
  email: 'Email',
  username: 'Username',
  password: 'Password',
  currentPassword: 'Current Password',
  newPassword: 'New Password',
  confirmPassword: 'Confirm Password',
  invitationCode: 'Invitation Code',
  keepMeSignedIn: 'Keep me signed in',
  forgotPassword: 'Forgot password?',
  doNotHaveAnAccount: 'Do not have an account?',
  alreadyHaveAnAccount: 'Already have an account?',
  thisFieldIsRequired: 'This field is required',
  thisFieldIsInvalid: 'This field is invalid',
  yourEmailIsInvalid: 'Your Email is invalid',
  makeSureSameToPassword: 'Make sure same to password',
  minLength: 'Min Length: ',
  maxLength: 'Max Length: ',
  min: 'Min: ',
  max: 'Max: ',
  agreeTheTermsAndPolicy: 'Agree the terms and policy',
  pleaseAcceptThis: 'Please accept this',
  refresh: 'Refresh',
  adminPanel: 'Admin Panel',
  userManagement: 'User Management',
  dashboard: 'Dashboard',
  yes: 'Yes',
  no: 'No',
  back: 'Back',
  save: 'Save',
  ok: 'OK',
  doYouWantToSignOut: 'Do you want to sign out?',
  exitConfirmation: 'Exit Confirmation',
  doYouWantToQuit: 'Do you want to quit?',

  deleteUser: 'Delete User',
  doYouWantToDelete: 'Do you want to delete?',
  doYouWantToDelete2: 'Do you want to delete',

  addUser: 'Add User',
  editUser: 'Edit User',
  add: 'Add',
  edit: 'Edit',
  cancel: 'Cancel',
  thisEmailIsInvalid: 'This email is invalid',
  delete: 'Delete',

  newApiKey: 'New Api Key',
  createBot: 'Create Bot',
  startBot: 'Start Bot',
  editBot: 'Edit Bot',
  deleteBot: 'Delete Bot',
  stopBot: 'Stop Bot',

  apikey: 'Apikey',
  registerApikeys: 'Register Apikeys',
  testnet: 'Testnet',
  net: 'Net',

  registerBots: 'Create Bots',
  name: 'Name',
  exchange: 'Exchange',
  symbol: 'Symbol',
  apiKey: 'Api Key',
  apiKeySecret: 'Api Key Sercet',
  orderType: 'Order Type',
  strategy: 'Strategy',
  leverage: 'Leverage',
  quantity: 'Quantity',
  price: 'Price',
  tpPercent: 'T/P %',
  takeProfitPercent: 'Take Profit %',
  slPercent: 'S/L %',
  stopLossPercent: 'Stop Loss %',
  market: 'Market',
  limit: 'Limit',
  postOnly: 'Post Only',
  long: 'Long',
  short: 'Short',
  cross: 'Cross',
  custom: 'Custom',
  trailingStop: 'Trailing Stop %',
  numberOfSafeOrder: 'Number Of Safe Order',
  actionForLoss: 'Action For Loss',
  actionForProfit: 'Action For Profit',
  closeTheOrder: 'Close the order',
  openNewOrderOnStopLossPrice: 'Open new order on stop loss price',
  valueXOfLastCloseOrder: 'Value(X) Of Last Close Order',
  timesRepeatSameLogic: 'Times repeat same logic',
  breakdownPriceForNewOrder: 'Breakdown price for new order',
  timeIntervalAfterClose: 'Time interval after close',
  selectExchange: '(Select Exchange)',
  selectSymbol: '(Select Symbol)',
  botLogicBasedOn: 'Bot Logic Based On',
  signal: 'Signal',
  leverageX: 'Leverage(X)',
  closeOnTrigger: 'Close on Trigger',
  placeOrder: 'Place Order',
  limitPrice: 'Limit Price',
  buyLong: 'Buy/Long',
  sellShort: 'Sell/Short',
  takeProfitMarket: 'Take Profit Market',
  triggerPrice: 'Trigger Price',
  orderDetails: 'Order Details',
  value: 'Value',
  entryPrice: 'Entry Price',
  markPrice: 'Mark Price',
  liqPrice: 'Liq Price',
  margin: 'Margin',
  closeOrderDetails: 'Close Order Details',
  qty: 'Qty',
  orderPrice: 'Order Price',
  filled: 'Filled',
  stopPrice: 'Stop Price',
  triggeringPrice: 'Triggering Price',
  saveBotData: 'Save Bot Data',
  backToMain: 'Back to Main',

  settings: 'Settings',
  connetAnExchange: 'Connect an exchange',
  confirmPasswordIsNotMatchWithNewPassword: 'Confirm Password is not match with new password',
  change: 'Change',
  changePassword: 'Change Password',
  resetPassword: 'Reset Password',
  personalChart: 'Personal Chart',
  clear: 'Clear',
  connect: 'Connect',
  connected: 'Connected',
  disconnect: 'Disconnect',
  disconnected: 'Disconnected',
  total: 'Total',
  size: 'Size',
  walletBalance: 'Wallet Balance',
  unrealizedPNL: 'Unrealised PNL',
  marginBalance: 'Margin Balance',
  positionMargin: 'Position Margin',
  orderMargin: 'Order Margin',
  availableBalance: 'Available Balance',
  doYouWantToDisconnect: 'Do you want to disconnect?',
  doYouWantToDisconnect2: 'Now connected to exchange. Do you want to disconnect and clear?',

  doYouWantToStop: 'Do you want to stop?',
  generalReply: 'General reply',
  botOrder: 'Bot Order',
  botStatus: 'Bot Status',

  tradingviewPersonalChartId: 'Tradingview personal Chart ID',
};
